### ISSUE TITLE
How do you test custom questions locally?

### ISSUE THREAD

**Issue by joe-engalan** [Learnosity/custom-questions-skeleton#3]
Where do you run 'yarn dev' from to test your questions locally?

 If you build a custom question and run yarn dev, localhost:12345 gives this error:

The requested resource / was not found on this server
<img width="444" alt="Screen Shot 2021-12-08 at 1 34 06 PM" src="https://user-images.githubusercontent.com/6577542/145264491-8372e359-87f0-4d83-a25f-5a0b1b3187a4.png">
.

**Comment by ColinSaltire** [comment]
There is an authoring page at localhost:12345/authoring.php, and an assessment page at localhost:12345/assessment.php

**Comment by gonzalozawa** [comment]
This has been added to the README https://github.com/Learnosity/custom-questions-skeleton/blob/master/README.md#test-your-custom-question

Thanks for the feedback!
