### ISSUE TITLE
Struggling Running Demo

### ISSUE THREAD

**Issue by bibobanna** [Learnosity/custom-questions-skeleton#63]
Hi,

So I just want to run one of the demos in my env. I have the clock dist folder. How do I incorporate it into my Question Editor?

**Comment by PhilBroadbent** [comment]
Hi @bibobanna - sorry for not getting back to you sooner.

By "my Question Editor", do you mean your own implementation within your product?

If so, you can copy the various pieces over, like so:
- Pass the Question Editor init options found [here](https://github.com/Learnosity/custom-questions-skeleton/blob/master/demos/clock/question_editor_init_options.json). Note: If you're using Author API, you can pass them in via the dependencies object [here](https://help.learnosity.com/hc/en-us/articles/16852477989405-config-dependencies-question-editor-api-init-options-Initialization-Author-API). 
- Copy over the HTML layout (clock_question_authoring.html), question JS (question.js) and scoring JS (scorer.js). You may need to adjust the `editor_layout`, `question` and `scorer` paths in the init options to point to the correct location of these files.

That should be it - now when you instantiate the API it will see the custom question init options and use them to add a new tile and then clicking on that will take you to the custom question.
